# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and canary builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: [stage]
  pull_request:
    branches: [stage, main]

jobs:
  check-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2

      - run: deno task check:all

      - name: Push to main
        if: ${{ github.event_name == 'push' && success() }}
        run: |
          git fetch origin $(git branch --show-current) --depth=50
          git push origin HEAD:main
